const sections = [
  {
    title: "About the reading",
    items: [
      {
        q: "What is Chinese astrology?",
        a: "Chinese astrology is a family of symbolic systems that map birth time and calendar cycles to personality traits and life themes. We present it as cultural wisdom for self-reflection and entertainment—not as scientific certainty.",
      },
      {
        q: "Is this fortune telling?",
        a: "We do not claim to predict fixed outcomes. Readings describe patterns and possibilities so you can reflect with more clarity. Treat insights as prompts, not commands.",
      },
      {
        q: "Is it scientifically proven?",
        a: "Astrology is not a substitute for professional advice in medicine, law, finance, or mental health. It is a reflective framework; use your judgment and seek experts when needed.",
      },
    ],
  },
  {
    title: "Accuracy",
    items: [
      {
        q: "Do I need birth time?",
        a: "Birth time improves precision for certain chart elements. If unknown, use your best estimate or skip time—your report still highlights useful themes, with a narrower technical scope.",
      },
      {
        q: "How accurate is the report?",
        a: "Quality depends on correct birth data and how you apply the insights. Reports are generated by AI from classical-style rules; they are best used as structured reflection, not literal prediction.",
      },
      {
        q: "Should I use this for major life decisions?",
        a: "No. Use readings for reflection and planning conversations—not as the sole basis for medical, legal, financial, or safety decisions.",
      },
    ],
  },
  {
    title: "Purchase",
    items: [
      {
        q: "How do I receive my report?",
        a: "After checkout, you receive your reading through the secure delivery flow shown in the product (for example, email or on-screen download). Exact steps are confirmed at purchase.",
      },
      {
        q: "What is your refund policy?",
        a: "Refund terms depend on the product version and region. We publish the current policy on the checkout page and in your confirmation email. Contact support if delivery fails.",
      },
      {
        q: "What currency are prices in?",
        a: "Prices are shown in USD unless stated otherwise at checkout. Your bank may apply conversion fees for non-USD cards.",
      },
    ],
  },
  {
    title: "Privacy",
    items: [
      {
        q: "Do you store birth data?",
        a: "We collect only what is needed to generate your chart and deliver your order. Retention, deletion, and security measures are described in our Privacy Policy.",
      },
      {
        q: "Who can access my information?",
        a: "Access is limited to systems and people required to run the service (for example, delivery and support). We do not sell personal data.",
      },
      {
        q: "Can I request deletion?",
        a: "Yes, where applicable by law and our internal policies. Use the contact options in our Privacy Policy to request deletion or export.",
      },
    ],
  },
];

export default function FAQList() {
  return (
    <div className="mt-12 space-y-14">
      {sections.map((section) => (
        <section key={section.title}>
          <h2 className="text-xl font-semibold text-zinc-900">{section.title}</h2>
          <div className="mt-6 space-y-4">
            {section.items.map((item) => (
              <details
                key={item.q}
                className="group rounded-xl border border-zinc-200 bg-white p-4 open:shadow-sm"
              >
                <summary className="cursor-pointer list-none font-medium text-zinc-900 after:float-right after:text-zinc-400 after:content-['+'] open:after:content-['−']">
                  {item.q}
                </summary>
                <p className="mt-3 text-sm leading-relaxed text-zinc-600">{item.a}</p>
              </details>
            ))}
          </div>
        </section>
      ))}
    </div>
  );
}
